# Croatian Labor Law Fact Checker - GitHub Pages Deployment
name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g htmlhint stylelint eslint
          npm install -g clean-css-cli terser

      - name: Validate HTML
        run: |
          htmlhint index.html --config .htmlhintrc || true
          echo "HTML validation completed"

      - name: Validate CSS
        run: |
          stylelint "src/styles/**/*.css" --config .stylelintrc.json || true
          echo "CSS validation completed"

      - name: Validate JavaScript
        run: |
          # Only lint existing JavaScript files
          find src -name "*.js" -type f | head -10 | while read file; do
            echo "Linting $file"
            eslint "$file" --config .eslintrc.json || echo "ESLint warning for $file"
          done
          echo "JavaScript validation completed"

      - name: Optimize assets
        run: |
          # Create directory structure
          mkdir -p dist/src/styles dist/src/scripts dist/src/core dist/src/utils dist/src/data dist/src/search-engine dist/src/models dist/src/features dist/public dist/assets/icons
          
          # Copy original files first as fallback
          cp -r src/* dist/src/
          cp -r public/* dist/public/
          cp -r assets/* dist/assets/ 2>/dev/null || true
          cp manifest.json dist/ 2>/dev/null || true
          cp sw.js dist/ 2>/dev/null || true
          
          # Minify CSS (with error handling and fallbacks)
          if test -f src/styles/neumorphism.css; then
            cleancss -o dist/src/styles/neumorphism.min.css src/styles/neumorphism.css || cp src/styles/neumorphism.css dist/src/styles/neumorphism.min.css
            echo "Neumorphism CSS processed"
          fi
          
          if test -f src/styles/style.css; then
            cleancss -o dist/src/styles/style.min.css src/styles/style.css || cp src/styles/style.css dist/src/styles/style.min.css  
            echo "Style CSS processed"
          fi
          
          if test -f src/styles/enhanced.css; then
            cleancss -o dist/src/styles/enhanced.min.css src/styles/enhanced.css || cp src/styles/enhanced.css dist/src/styles/enhanced.min.css
            echo "Enhanced CSS processed"
          fi
          
          # Minify JavaScript (only existing files)
          test -f src/scripts/i18n.js && (terser src/scripts/i18n.js -o dist/src/scripts/i18n.min.js --compress --mangle || cp src/scripts/i18n.js dist/src/scripts/i18n.min.js)
          test -f src/scripts/main.js && (terser src/scripts/main.js -o dist/src/scripts/main.min.js --compress --mangle || cp src/scripts/main.js dist/src/scripts/main.min.js)
          test -f src/scripts/security.js && (terser src/scripts/security.js -o dist/src/scripts/security.min.js --compress --mangle || cp src/scripts/security.js dist/src/scripts/security.min.js)
          test -f src/scripts/gdpr.js && (terser src/scripts/gdpr.js -o dist/src/scripts/gdpr.min.js --compress --mangle || cp src/scripts/gdpr.js dist/src/scripts/gdpr.min.js)
          test -f src/scripts/feedback.js && (terser src/scripts/feedback.js -o dist/src/scripts/feedback.min.js --compress --mangle || cp src/scripts/feedback.js dist/src/scripts/feedback.min.js)
          test -f src/scripts/tests.js && (terser src/scripts/tests.js -o dist/src/scripts/tests.min.js --compress --mangle || cp src/scripts/tests.js dist/src/scripts/tests.min.js)
          
          # Minify Search Engine files (new structure)
          test -f src/search-engine/SearchEngine.js && (terser src/search-engine/SearchEngine.js -o dist/src/search-engine/SearchEngine.min.js --compress --mangle || cp src/search-engine/SearchEngine.js dist/src/search-engine/SearchEngine.min.js)
          test -f src/search-engine/SearchManager.js && (terser src/search-engine/SearchManager.js -o dist/src/search-engine/SearchManager.min.js --compress --mangle || cp src/search-engine/SearchManager.js dist/src/search-engine/SearchManager.min.js)
          
          # Minify Core files
          test -f src/core/LegalDatabase.js && (terser src/core/LegalDatabase.js -o dist/src/core/LegalDatabase.min.js --compress --mangle || cp src/core/LegalDatabase.js dist/src/core/LegalDatabase.min.js)
          
          # Minify Utils (only existing files)
          test -f src/utils/TextProcessor.js && (terser src/utils/TextProcessor.js -o dist/src/utils/TextProcessor.min.js --compress --mangle || cp src/utils/TextProcessor.js dist/src/utils/TextProcessor.min.js)
          test -f src/utils/CacheManager.js && (terser src/utils/CacheManager.js -o dist/src/utils/CacheManager.min.js --compress --mangle || cp src/utils/CacheManager.js dist/src/utils/CacheManager.min.js)
          test -f src/utils/ExportManager.js && (terser src/utils/ExportManager.js -o dist/src/utils/ExportManager.min.js --compress --mangle || cp src/utils/ExportManager.js dist/src/utils/ExportManager.min.js)
          test -f src/utils/Validator.js && (terser src/utils/Validator.js -o dist/src/utils/Validator.min.js --compress --mangle || cp src/utils/Validator.js dist/src/utils/Validator.min.js)
          
          # Create optimized index.html
          cp index.html dist/index.html
          
          # Replace paths to minified versions only if the minified files exist
          if test -f dist/src/styles/neumorphism.min.css; then
            sed -i 's/src\/styles\/neumorphism\.css/src\/styles\/neumorphism.min.css/g' dist/index.html
          fi
          
          if test -f dist/src/styles/style.min.css; then
            sed -i 's/src\/styles\/style\.css/src\/styles\/style.min.css/g' dist/index.html
          fi
          
          if test -f dist/src/styles/enhanced.min.css; then
            sed -i 's/src\/styles\/enhanced\.css/src\/styles\/enhanced.min.css/g' dist/index.html  
          fi
          
          if test -f dist/src/scripts/main.min.js; then
            sed -i 's/src\/scripts\/main\.js/src\/scripts\/main.min.js/g' dist/index.html
          fi
          
          # Continue with other replacements for existing files
          test -f dist/src/core/LegalDatabase.min.js && sed -i 's/src\/core\/LegalDatabase\.js/src\/core\/LegalDatabase.min.js/g' dist/index.html
          test -f dist/src/search-engine/SearchEngine.min.js && sed -i 's/src\/search-engine\/SearchEngine\.js/src\/search-engine\/SearchEngine.min.js/g' dist/index.html
          test -f dist/src/search-engine/SearchManager.min.js && sed -i 's/src\/search-engine\/SearchManager\.js/src\/search-engine\/SearchManager.min.js/g' dist/index.html
          test -f dist/src/scripts/i18n.min.js && sed -i 's/src\/scripts\/i18n\.js/src\/scripts\/i18n.min.js/g' dist/index.html
          test -f dist/src/scripts/security.min.js && sed -i 's/src\/scripts\/security\.js/src\/scripts\/security.min.js/g' dist/index.html
          test -f dist/src/scripts/gdpr.min.js && sed -i 's/src\/scripts\/gdpr\.js/src\/scripts\/gdpr.min.js/g' dist/index.html
          test -f dist/src/scripts/feedback.min.js && sed -i 's/src\/scripts\/feedback\.js/src\/scripts\/feedback.min.js/g' dist/index.html
          test -f dist/src/scripts/tests.min.js && sed -i 's/src\/scripts\/tests\.js/src\/scripts\/tests.min.js/g' dist/index.html
          
          echo "Asset optimization completed"

      - name: Generate sitemap
        run: |
          cat > dist/sitemap.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/</loc>
              <lastmod>$(date -u +%Y-%m-%dT%H:%M:%S+00:00)</lastmod>
              <changefreq>weekly</changefreq>
              <priority>1.0</priority>
            </url>
          </urlset>
          EOF
          echo "Sitemap generated"

      - name: Generate robots.txt
        run: |
          cat > dist/robots.txt << 'EOF'
          User-agent: *
          Allow: /
          
          Sitemap: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/sitemap.xml
          EOF
          echo "Robots.txt generated"

      - name: Create manifest.json
        run: |
          cat > dist/manifest.json << 'EOF'
          {
            "name": "Croatian Labor Law Fact Checker",
            "short_name": "HR Labor Law",
            "description": "Comprehensive tool for checking Croatian workers' rights and labor laws",
            "start_url": "/",
            "display": "standalone",
            "background_color": "#ffffff",
            "theme_color": "#ffffff",
            "icons": [
              {
                "src": "assets/icons/favicon-32x32.png",
                "sizes": "32x32",
                "type": "image/png"
              },
              {
                "src": "assets/icons/favicon.svg",
                "sizes": "any",
                "type": "image/svg+xml"
              }
            ]
          }
          EOF
          echo "PWA manifest created"

      - name: Create service worker
        run: |
          cat > dist/sw.js << 'EOF'
          const CACHE_NAME = 'croatian-labor-law-v2';
          const urlsToCache = [
            '/',
            '/src/styles/neumorphism.min.css',
            '/src/styles/style.min.css',
            '/src/styles/enhanced.min.css',
            '/src/scripts/i18n.min.js',
            '/src/scripts/main.min.js',
            '/src/scripts/security.min.js',
            '/src/scripts/gdpr.min.js',
            '/src/scripts/feedback.min.js',
            '/src/core/LegalDatabase.min.js',
            '/src/search-engine/SearchEngine.min.js',
            '/src/search-engine/SearchManager.min.js',
            '/src/search-engine/data/croatian-labor-law.json',
            '/src/data/translations.json'
          ];

          self.addEventListener('install', event => {
            event.waitUntil(
              caches.open(CACHE_NAME)
                .then(cache => cache.addAll(urlsToCache.filter(url => url !== '/src/scripts/search.min.js')))
                .catch(err => console.log('Cache install failed:', err))
            );
          });

          self.addEventListener('fetch', event => {
            event.respondWith(
              caches.match(event.request)
                .then(response => {
                  if (response) {
                    return response;
                  }
                  return fetch(event.request);
                }
              ).catch(err => {
                console.log('Fetch failed:', err);
                return fetch(event.request);
              })
            );
          });
          EOF
          echo "Service worker created"

      - name: Run performance audit
        run: |
          # Install Lighthouse CI
          npm install -g @lhci/cli
          
          # Start server for testing
          cd dist
          python3 -m http.server 9090 &
          cd ..
          sleep 5
          
          # Create Lighthouse CI config
          cat > lighthouserc.json << 'EOF'
          {
            "ci": {
              "collect": {
                "url": ["http://localhost:9090"],
                "startServerCommand": "cd dist && python3 -m http.server 9090",
                "numberOfRuns": 1
              },
              "assert": {
                "assertions": {
                  "categories:performance": ["warn", {"minScore": 0.8}],
                  "categories:accessibility": ["error", {"minScore": 0.9}],
                  "categories:best-practices": ["warn", {"minScore": 0.8}],
                  "categories:seo": ["warn", {"minScore": 0.8}]
                }
              }
            }
          }
          EOF
          
          # Run Lighthouse audit
          lhci autorun || true
          echo "Performance audit completed"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Post-deployment verification
  verify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Verify deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Site URL: ${{ needs.deploy.outputs.url }}"
          
          # Wait for deployment to be available
          sleep 30
          
          # Basic health check
          curl -I "${{ needs.deploy.outputs.url }}" || echo "Health check completed"
          
          echo "Verification completed"
